### ISSUE TITLE
Improvement of Verification system eBMS

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#738]
There are several issues with the verification system. I am promoting the use of this system to national and regional coordinators and new verifiers on butterflies, moths and dragonflies. I created several issues explaining each one in a separated issue, here you can see:

- [ ] validated records stay on pending status #737 
- [x] pop-up message #725
- [x] better filters on verification #735 
- [ ] strict flight period #724 
- [ ] improve assign verifiers #736 

@DavidRoy I know this will take some time, but verification is important to improve data that Reto is collecting to update the new version of eBMS database. I would like to give this more priority at the moment. Thanks
